### ISSUE TITLE
more button codes

### ISSUE THREAD

**Issue by torinnguyen** [codedealer/livolo#1]
I'm using the following codes in Arduino library.

//Mini remote       #A: 8, #B: 16, #C: 56, #OFF: 42
//Fullsize remote   #1: 0, #2: 96, #3: 120, #4: 24, #5: 80, #6: 48, #7: 108, #8: 12, #9: 72; #10 (0): 40, #OFF: 106
//#scene1: 90, #scene2: 114, #scene3: 10, #scene4: 18
//dimmer+L: 92, dimmer-L: 116, dimmer+R: 126, dimmer-R: 26

//Real full remotes ID: 1 + 3*remote_index
//Real mini remotes: numbers that are not full remote ID

**Comment by codedealer** [comment]
Thanks for sharing! I added the information to readme.
