### ISSUE TITLE
Some basic tips

### ISSUE THREAD

**Issue by muscaiu** [codedealer/livolo#2]
I found this tutorial on getting started and it worked for turning on and off one switch. ( https://www.instructables.com/id/Controlling-a-Livolo-RF-Light-Switch-Using-a-Raspb/ )

I have an emmiter and transmitter just like in the tutorial and i'm hoping to read/pair the switch signal and then send it back to it to turn it on and off.

Can something similar be achieved with this library?
Is there any other library for a node server?
Thanks!

**Comment by codedealer** [comment]
Hi, this library only supports transmitting signals, you can't read anything with it. However you can use the working codes provided in Readme to pair your livolo switch with any of those.

Press the button on the switch for 5 seconds until you hear the beeping sound then hit send with any of the example codes from your RPi.

As far as I know there weren't any other nodejs libs for RPis maybe that changed but it's unlikely.

**Comment by muscaiu** [comment]
I'm thinking of buying more Livolo switches to add them to my home automation with RPI, but i have some doubts. 
Right now i guess i can toggle it on and off, but i'm wondering if it's possible to also get the `status` of the switch.
Do you think this is possible? Because otherwise it wouldn't make much of an automaton just to turn it on and off.

**Comment by codedealer** [comment]
There are new ones that support zigbee standard. They have two way communication support but you have to buy livolo zigbee-wifi gate which is kind of inconvenient.

**This library does not support them**. This one is for older rf ones and those have only rf receiver meaning they can't send you a status report.

If you're looking for switches with status update I think your best option will be more expensive wi-fi based ones like Hue or z-wave based ones (there is a z-wave usb stick for RPi available). Or you can try livolo zigbee switches but you'll have to buy their wifi gate as well or reverse engineer the protocol they use by yourself.
